# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

# There are many options which enable SPI, so make this library available

obj-$(CONFIG_AW_REMOTEPROC) += sunxi_rproc.o
obj-$(CONFIG_BOOT_RISCV) += sunxi_rproc_riscv.o
obj-$(CONFIG_AW_RPROC_MISC_OPS) += sunxi_rproc_misc.o
obj-$(CONFIG_AW_RPROC_RSC_HELPER) += sunxi_rproc_rsc_helper.o
obj-$(CONFIG_AW_RPROC_USER_RESOURCE) += sunxi_rproc_user_resource.o
